('Gobernador (a) del Departamento de Cochabamba ','GOBERNADOR (A)','1',12556,1,11,NULL,NULL,NULL),
('Vocero Gubernativo del Órgano Ejecutivo ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','2',9623,4,11,NULL,NULL,NULL),
('Chofer - Mensajero I del Despacho de la Gobernación ','ADMINISTRATIVO II ','3',3347,17,11,NULL,NULL,NULL),
('Chofer - Mensajero II del Despacho de la Gobernación ','ADMINISTRATIVO II ','4',3347,17,11,NULL,NULL,NULL),
('Secretaria  – Asistente del Despacho de la Gobernación ','APOYO ADMINISTRATIVO I ','5',3100,19,11,NULL,NULL,NULL),
('Técnica  Administrativo de Seguimiento a Recomendaciones de Auditorías y Apoyo a Comité de Seguimiento de Control Interno. ','PROFESIONAL I','6',6000,9,11,NULL,NULL,NULL),
('Directora  Jurídico ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','7',9623,4,NULL,23,NULL,NULL),
('Técnico de Dirección Jurídica ','PROFESIONAL I','8',6000,9,NULL,23,NULL,NULL),
('Secretaria  – Asistente de Dirección Jurídica ','APOYO ADMINISTRATIVO II','9',2800,21,NULL,23,NULL,NULL),
('Chofer - Mensajero de Dirección Jurídica ','APOYO ADMINISTRATIVO II','10',2800,21,NULL,23,NULL,NULL),
('Responsable del Área Jurídica Procesal ','PROFESIONAL I','11',6000,9,NULL,NULL,NULL,29),
('Encargado de Procesos Penales. ','PROFESIONAL I','12',6000,9,NULL,NULL,NULL,29),
('Encargada I de Procesos Coactivos Fiscales, Contenciosos y Administrativos. ','PROFESIONAL I','13',6000,9,NULL,NULL,NULL,29),
('Encargada  II de Procesos Coactivos Fiscales, contenciosos y administrativos. ','PROFESIONAL I','14',6000,9,NULL,NULL,NULL,29),
('Encargada  de Procesos Civiles, Constitucionales, Laborales, Contenciosos. ','PROFESIONAL I','15',6000,9,NULL,NULL,NULL,29),
('Asistente Auxiliar del Área Jurídica Procesal ','APOYO ADMINISTRATIVO I ','16',3100,19,NULL,NULL,NULL,29),
('Jefe de Unidad Jurídica Administrativa, Legislativa y Gaceta Oficial Departamental. ','JEFA (E) DE UNIDAD','17',8554,5,NULL,NULL,25,NULL),
('Técnica  I en Asuntos Administrativos y Normativos ','PROFESIONAL I','18',6000,9,NULL,NULL,25,NULL),
('Técnico II en Asuntos Administrativos y Normativos ','PROFESIONAL I','19',6000,9,NULL,NULL,25,NULL),
('Técnico III en Asuntos Administrativos y Normativos ','PROFESIONAL I','20',6000,9,NULL,NULL,25,NULL),
('Técnica  IV en Asuntos Administrativos y Normativos ','PROFESIONAL I','21',6000,9,NULL,NULL,25,NULL),
('Técnica  V en Asuntos Administrativos y Normativos ','PROFESIONAL I','22',6000,9,NULL,NULL,25,NULL),
('Técnico VI en Asuntos Administrativos y Normativos ','PROFESIONAL I','23',6000,9,NULL,NULL,25,NULL),
('Técnica VII en Asuntos Administrativos y Normativos ','PROFESIONAL I','24',6000,9,NULL,NULL,25,NULL),
('Técnico en Desarrollo y Gestión Legislativa ','PROFESIONAL II','25',4622,11,NULL,NULL,25,NULL),
('Técnico  de Gaceta Oficial Departamental ','ADMINISTRATIVO II ','26',3347,17,NULL,NULL,25,NULL),
('Director  de Comunicación Social ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','27',9623,4,NULL,24,NULL,NULL),
('Encargada  de Contenidos y Políticas Comunicacionales. ','PROFESIONAL I','28',6000,9,NULL,24,NULL,NULL),
('Encargado de Prensa ','PROFESIONAL I','29',6000,9,NULL,24,NULL,NULL),
('Encargado de Producción Audiovisual ','PROFESIONAL II','30',4622,11,NULL,24,NULL,NULL),
('Encargada  de Coordinación con Medios de Comunicación y Prensa. ','ADMINISTRATIVO II ','31',3347,17,NULL,24,NULL,NULL),
('Técnico en Diseño Gráfico y Apoyo en Producción Audiovisual. ','ADMINISTRATIVO II ','32',3347,17,NULL,24,NULL,NULL),
('Secretaria - Asistente de la Dirección de Comunicación Social. ','APOYO ADMINISTRATIVO II','33',2800,21,NULL,24,NULL,NULL),
('Chofer-Mensajero de la Dirección de Comunicación Social. ','APOYO ADMINISTRATIVO II','34',2800,21,NULL,24,NULL,NULL),
('Encargado del Área de Tecnologías de Información ','PROFESIONAL II','35',4622,11,NULL,NULL,NULL,30),
('Técnica (o) en Digitalización e Innovación de Información y Comunicación. ','PROFESIONAL II','36',4622,11,NULL,NULL,NULL,30),
('Jefa de Unidad de Gabinete y Protocolo ','JEFA (E) DE UNIDAD','37',8554,5,NULL,NULL,26,NULL),
('Técnico - Administrativo de la Unidad de Gabinete y Protocolo ','PROFESIONAL I','38',6000,9,NULL,NULL,26,NULL),
('Técnica de la Unidad de Gabinete y Protocolo ','PROFESIONAL II','39',4622,11,NULL,NULL,26,NULL),
('Asistente de Relaciones Públicas y Protocolo ','ADMINISTRATIVO II ','40',3347,17,NULL,NULL,26,NULL),
('Asistente de Protocolo y Ceremonial ','ADMINISTRATIVO II ','41',3347,17,NULL,NULL,26,NULL),
('Asistente de la Unidad de Gabinete y Protocolo ','APOYO ADMINISTRATIVO I ','42',3100,19,NULL,NULL,26,NULL),
('Chofer - Mensajero de la Unidad de Gabinete y Protocolo ','APOYO ADMINISTRATIVO I ','43',3100,19,NULL,NULL,26,NULL),
('Encargada  del Área de Recepción de Correspondencia y Atención al Ciudadano. ','ADMINISTRATIVO II ','44',3347,17,NULL,NULL,NULL,31),
('Apoyo de Recepción y Atención al Ciudadano ','APOYO ADMINISTRATIVO II','45',2800,21,NULL,NULL,NULL,31),
('Apoyo de Recepción y Despacho de Correspondencia ','ASISTENTE ','46',2760,22,NULL,NULL,NULL,31),
('Jefa de Unidad de Auditoría Interna ','JEFA (E) DE UNIDAD','47',8554,5,NULL,NULL,27,NULL),
('Supervisoro I de Auditorías ','PROFESIONAL I','48',6000,9,NULL,NULL,27,NULL),
('Supervisoro II de Auditorías ','PROFESIONAL I','49',6000,9,NULL,NULL,27,NULL),
('Supervisora III de Auditorías ','PROFESIONAL I','50',6000,9,NULL,NULL,27,NULL),
('Técnica I de Auditorias ','PROFESIONAL II','51',4622,11,NULL,NULL,27,NULL),
('Técnico II de Auditorias ','PROFESIONAL II','52',4622,11,NULL,NULL,27,NULL),
('Técnico III de Auditorias ','PROFESIONAL II','53',4622,11,NULL,NULL,27,NULL),
('Secretaria – Asistente de la Unidad de Auditoría Interna. ','APOYO ADMINISTRATIVO II','54',2800,21,NULL,NULL,27,NULL),
('Chofer – Mensajero de la Unidad de Auditoría Interna ','APOYO ADMINISTRATIVO II','55',2800,21,NULL,NULL,27,NULL),
('Jefe de Unidad de Transparencia y Participación Social. ','JEFA (E) DE UNIDAD','56',8554,5,NULL,NULL,28,NULL),
('Técnico I de la Unidad de Transparencia y Participación Social. ','PROFESIONAL II','57',4622,11,NULL,NULL,28,NULL),
('Técnico II de la Unidad de Transparencia y Participación Social ','PROFESIONAL II','58',4622,11,NULL,NULL,28,NULL),
('Secretario - Asistente de la Unidad de Transparencia y Participación Social. ','APOYO ADMINISTRATIVO II','59',2800,21,NULL,NULL,28,NULL),
('Jefe de Unidad de Gestión de Recursos Humanos ','JEFA (E) DE UNIDAD','60',8554,5,NULL,NULL,29,NULL),
('Coordinador Técnico Administrativo y Gestión Normativa de Recursos Humanos. ','PROFESIONAL I','61',6000,9,NULL,NULL,29,NULL),
('Encargado de Planillas ','PROFESIONAL II','62',4622,11,NULL,NULL,29,NULL),
('Técnica de Gestión de Recursos Humanos ','PROFESIONAL II','63',4622,11,NULL,NULL,29,NULL),
('Técnica  de Dotación de Personal ','ADMINISTRATIVO I','64',3925,13,NULL,NULL,29,NULL),
('Técnica I de Control y Seguimiento de Personal ','ADMINISTRATIVO I','65',3925,13,NULL,NULL,29,NULL),
('Técnico II de Control y Seguimiento de Personal ','ADMINISTRATIVO I','66',3925,13,NULL,NULL,29,NULL),
('Técnico de Registro de Personal e Inventario ','APOYO ADMINISTRATIVO I ','67',3100,19,NULL,NULL,29,NULL),
('Asistente de Trámites Administrativos ','APOYO ADMINISTRATIVO II','68',2800,21,NULL,NULL,29,NULL),
('Secretaria – Asistente de la Unidad de Gestión Recursos Humanos. ','APOYO ADMINISTRATIVO II','69',2800,21,NULL,NULL,29,NULL),
('Secretario Departamental de Planificación y Desarrollo Estratégico ','SECRETARIA (O) DEPARTAMENTAL','70',10577,3,12,NULL,NULL,NULL),
('Administrador (a) – Coordinador (a) de la SDPyDE ','PROFESIONAL I','71',6000,9,12,NULL,NULL,NULL),
('Secretaria – Asistente de la SDPyDE ','APOYO ADMINISTRATIVO I ','72',3100,19,12,NULL,NULL,NULL),
('Chofer - Mensajero de la SDPyDE ','APOYO ADMINISTRATIVO I ','73',3100,19,12,NULL,NULL,NULL),
('Asistente-Mensajero de la SDPyDE ','APOYO ADMINISTRATIVO II','74',2800,21,12,NULL,NULL,NULL),
('Jefe de Unidad de Planeación Estratégica y Programación Operativa. ','JEFA (E) DE UNIDAD','75',8554,5,NULL,NULL,30,NULL),
('Técnica I en Planeación Estratégica y Programación Operativa, Seguimiento y Evaluación. ','PROFESIONAL I','76',6000,9,NULL,NULL,30,NULL),
('Técnica II en Planeación Estratégica y Programación Operativa, Seguimiento y Evaluación. ','PROFESIONAL I','77',6000,9,NULL,NULL,30,NULL),
('Técnico III en Planeación Estratégica en Programación Operativa, Seguimiento y Evaluación. ','PROFESIONAL I','78',6000,9,NULL,NULL,30,NULL),
('Técnico IV en Planeación Estratégica en Programación Operativa, Seguimiento y Evaluación. ','PROFESIONAL II','79',4622,11,NULL,NULL,30,NULL),
('Técnica de Información Institucional y Estadística ','PROFESIONAL II','80',4622,11,NULL,NULL,30,NULL),
('Secretaria – Asistente de Planeación Estratégica y Programación Operativa. ','APOYO ADMINISTRATIVO II','81',2800,21,NULL,NULL,30,NULL),
('Jefe de Unidad de Organización y Métodos ','JEFA (E) DE UNIDAD','82',8554,5,NULL,NULL,31,NULL),
('Técnica Analista I de Organización y Métodos ','PROFESIONAL I','83',6000,9,NULL,NULL,31,NULL),
('Técnica Analista II de Organización y Métodos ','PROFESIONAL II','84',4622,11,NULL,NULL,31,NULL),
('Técnico Analista III de Organización y Métodos ','PROFESIONAL II','85',4622,11,NULL,NULL,31,NULL),
('Secretaria - Asistente de la Unidad de Organización y Métodos. ','APOYO ADMINISTRATIVO II','86',2800,21,NULL,NULL,31,NULL),
('Jefe de Unidad de Gestión de Programas y Proyectos ','JEFA (E) DE UNIDAD','87',8554,5,NULL,NULL,32,NULL),
('Técnico I en Gestión de Programas y Proyectos. ','PROFESIONAL I','88',6000,9,NULL,NULL,32,NULL),
('Técnico II en Gestión de Programas y Proyectos. ','PROFESIONAL I','89',6000,9,NULL,NULL,32,NULL),
('Técnica III en Gestión de Programas y Proyectos. ','PROFESIONAL I','90',6000,9,NULL,NULL,32,NULL),
('Técnico IV en Gestión de Programas y Proyectos. ','PROFESIONAL I','91',6000,9,NULL,NULL,32,NULL),
('Secretaria – Asistente de la UGPyP ','APOYO ADMINISTRATIVO II','92',2800,21,NULL,NULL,32,NULL),
('Jefe de Unidad de Coordinación con Regiones ','JEFA (E) DE UNIDAD','93',8554,5,NULL,NULL,33,NULL),
('Técnica Sectorialista I de Coordinación con Regiones ','PROFESIONAL I','94',6000,9,NULL,NULL,33,NULL),
('Técnica Sectorialista II de Coordinación con Regiones. ','PROFESIONAL I','95',6000,9,NULL,NULL,33,NULL),
('Técnica Sectorialista III de Coordinación con Regiones. ','PROFESIONAL II','96',4622,11,NULL,NULL,33,NULL),
('Técnico Sectorialista IV de Coordinación con Regiones. ','PROFESIONAL II','97',4622,11,NULL,NULL,33,NULL),
('Secretario – Asistente de la UCR ','APOYO ADMINISTRATIVO II','98',2800,21,NULL,NULL,33,NULL),
('Secretario Departamental de Finanzas y Administración. ','SECRETARIA (O) DEPARTAMENTAL','99',10577,3,13,NULL,NULL,NULL),
('Administradora – Coordinadora de la SDFyA ','PROFESIONAL I','100',6000,9,13,NULL,NULL,NULL),
('Técnica de Gestión Administrativa ','PROFESIONAL I','101',6000,9,13,NULL,NULL,NULL),
('Secretaria – Asistente de la SDFyA ','APOYO ADMINISTRATIVO I ','102',3100,19,13,NULL,NULL,NULL),
('Chofer – Mensajero I de la SDFyA ','APOYO ADMINISTRATIVO I ','103',3100,19,13,NULL,NULL,NULL),
('Chofer – Mensajero II de la SDFyA ','APOYO ADMINISTRATIVO II','104',2800,21,13,NULL,NULL,NULL),
('Encargado de Área de Archivo Institucional ','ADMINISTRATIVO II ','105',3347,17,NULL,NULL,NULL,32),
('Auxiliar de Archivo Institucional ','ASISTENTE ','106',2760,22,NULL,NULL,NULL,32),
('Directora de Finanzas ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','107',9623,4,NULL,25,NULL,NULL),
('Secretaria – Asistente de la Dirección de Finanzas ','APOYO ADMINISTRATIVO II','108',2800,21,NULL,25,NULL,NULL),
('Jefa de Unidad de Contabilidad Fiscal ','JEFA (E) DE UNIDAD','109',8554,5,NULL,NULL,34,NULL),
('Analista Contable I ','PROFESIONAL I','110',6000,9,NULL,NULL,34,NULL),
('Analista Contable II ','PROFESIONAL I','111',6000,9,NULL,NULL,34,NULL),
('Analista de Gasto I ','PROFESIONAL II','112',4622,11,NULL,NULL,34,NULL),
('Analista de Gasto II ','PROFESIONAL II','113',4622,11,NULL,NULL,34,NULL),
('Analista de Gasto III ','PROFESIONAL II','114',4622,11,NULL,NULL,34,NULL),
('Técnico Contable ','ADMINISTRATIVO I','115',3925,13,NULL,NULL,34,NULL),
('Jefe de Unidad de Presupuestos ','JEFA (E) DE UNIDAD','116',8554,5,NULL,NULL,35,NULL),
('Encargada de Registro del Anteproyecto de Presupuesto y Modificaciones Presupuestarias. ','PROFESIONAL I','117',6000,9,NULL,NULL,35,NULL),
('Encargado de Certificaciones Presupuestarias ','PROFESIONAL II','118',4622,11,NULL,NULL,35,NULL),
('Técnico de Presupuestos ','ADMINISTRATIVO I','119',3925,13,NULL,NULL,35,NULL),
('Jefa de Unidad de Tesorería y Crédito Público ','JEFA (E) DE UNIDAD','120',8554,5,NULL,NULL,36,NULL),
('Encargada de Créditos y Garantías ','PROFESIONAL I','121',6000,9,NULL,NULL,36,NULL),
('Encargada Tributaria ','PROFESIONAL I','122',6000,9,NULL,NULL,36,NULL),
('Encargado de Recursos y Conciliación Bancaria ','PROFESIONAL II','123',4622,11,NULL,NULL,36,NULL),
('Encargada de Caja Central ','PROFESIONAL II','124',4622,11,NULL,NULL,36,NULL),
('Asistente Tributaria ','ADMINISTRATIVO II ','125',3347,17,NULL,NULL,36,NULL),
('Encargada de Priorización de Pago, Flujo de Caja y Acreedores ','ADMINISTRATIVO II ','126',3347,17,NULL,NULL,36,NULL),
('Asistente Auxiliar de la Unidad de Tesorería y Crédito Público ','APOYO ADMINISTRATIVO II','127',2800,21,NULL,NULL,36,NULL),
('Jefa de Unidad de Recaudación y Tributación ','JEFA (E) DE UNIDAD','128',8554,5,NULL,NULL,37,NULL),
('Técnico de Atención al Contribuyente, Gestión de Cobro y Cultura Tributaria. ','PROFESIONAL I','129',6000,9,NULL,NULL,37,NULL),
('Técnico de Normativa Tributaria y Fiscalización ','PROFESIONAL I','130',6000,9,NULL,NULL,37,NULL),
('Técnico de Fiscalización Tributaria ','ADMINISTRATIVO I','131',3925,13,NULL,NULL,37,NULL),
('Técnico de Caja Recaudadora ','ADMINISTRATIVO II ','132',3347,17,NULL,NULL,37,NULL),
('Técnica de Refrendo, Legalización y Archivo Tributario. ','ADMINISTRATIVO II ','133',3347,17,NULL,NULL,37,NULL),
('Técnica de Pre-liquidaciones y Plan de Pagos ','ADMINISTRATIVO II ','134',3347,17,NULL,NULL,37,NULL),
('Auxiliar Administrativo en Atención y Fiscalización Tributaria. ','APOYO ADMINISTRATIVO I ','135',3100,19,NULL,NULL,37,NULL),
('Jefa de Unidad de Contratación de Bienes y Servicios ','JEFA (E) DE UNIDAD','136',8554,5,NULL,NULL,38,NULL),
('Técnico I de Contrataciones Mayores ','PROFESIONAL I','137',6000,9,NULL,NULL,38,NULL),
('Técnica II de Contrataciones Mayores ','PROFESIONAL I','138',6000,9,NULL,NULL,38,NULL),
('Técnico I de Contrataciones Menores ','PROFESIONAL I','139',6000,9,NULL,NULL,38,NULL),
('Técnica II de Contrataciones Menores ','PROFESIONAL I','140',6000,9,NULL,NULL,38,NULL),
('Técnico Auxiliar de Contrataciones Mayores ','ADMINISTRATIVO I','141',3925,13,NULL,NULL,38,NULL),
('Técnica Auxiliar de Contrataciones Menores ','ADMINISTRATIVO I','142',3925,13,NULL,NULL,38,NULL),
('Secretaria – Asistente de la Unidad de Contratación de Bienes y Servicios. ','APOYO ADMINISTRATIVO II','143',2800,21,NULL,NULL,38,NULL),
('Jefa de Unidad de Administración de Bienes ','JEFA (E) DE UNIDAD','144',8554,5,NULL,NULL,39,NULL),
('Encargada I de Bienes Inmuebles ','PROFESIONAL II','145',4622,11,NULL,NULL,39,NULL),
('Encargado II de Bienes Inmuebles ','PROFESIONAL II','146',4622,11,NULL,NULL,39,NULL),
('Encargado del Sistema de Activos Fijos - Físico y Valorado. ','ADMINISTRATIVO I','147',3925,13,NULL,NULL,39,NULL),
('Encargado del Parque Automotor ','ADMINISTRATIVO I','148',3925,13,NULL,NULL,39,NULL),
('Encargado de Depósitos de Activos Fijos. ','ADMINISTRATIVO I','149',3925,13,NULL,NULL,39,NULL),
('Inventariadoro I de la Unidad de Administración de Bienes. ','APOYO ADMINISTRATIVO II','150',2800,21,NULL,NULL,39,NULL),
('Inventariadoro II de la Unidad de Administración de Bienes. ','APOYO ADMINISTRATIVO II','151',2800,21,NULL,NULL,39,NULL),
('Inventariador III de la Unidad de Administración de Bienes. ','APOYO ADMINISTRATIVO II','152',2800,21,NULL,NULL,39,NULL),
('Secretario – Asistente de la Unidad de Administración de Bienes. ','APOYO ADMINISTRATIVO II','153',2800,21,NULL,NULL,39,NULL),
('Encargada del Área de Almacenes ','PROFESIONAL II','154',4622,11,NULL,NULL,NULL,33),
('Auxiliar Administrativo I de Almacenes ','APOYO ADMINISTRATIVO II','155',2800,21,NULL,NULL,NULL,33),
('Auxiliar Administrativo II de Almacenes ','APOYO ADMINISTRATIVO II','156',2800,21,NULL,NULL,NULL,33),
('Encargado del Área de Transportes ','PROFESIONAL II','157',4622,11,NULL,NULL,NULL,34),
('Técnica en Manejo y Uso de Combustible ','ADMINISTRATIVO I','158',3925,13,NULL,NULL,NULL,34),
('Técnico de Maestranza y Mecánica ','ADMINISTRATIVO I','159',3925,13,NULL,NULL,NULL,34),
('Técnico en Mecánica General ','ADMINISTRATIVO II ','160',3347,17,NULL,NULL,NULL,34),
('Encargado del Área de Logística ','PROFESIONAL II','161',4622,11,NULL,NULL,NULL,35),
('Técnico I de Mantenimiento y Apoyo ','APOYO ADMINISTRATIVO II','162',2800,21,NULL,NULL,NULL,35),
('Técnico II de Mantenimiento y Apoyo ','APOYO ADMINISTRATIVO II','163',2800,21,NULL,NULL,NULL,35),
('Técnico III de Mantenimiento y Apoyo ','APOYO ADMINISTRATIVO II','164',2800,21,NULL,NULL,NULL,35),
('Auxiliar Administrativo del Área de Logística ','ASISTENTE ','165',2760,22,NULL,NULL,NULL,35),
('Portero/Sereno I ','ASISTENTE ','166',2760,22,NULL,NULL,NULL,35),
('Portero/Sereno II ','ASISTENTE ','167',2760,22,NULL,NULL,NULL,35),
('Portero/Sereno III ','ASISTENTE ','168',2760,22,NULL,NULL,NULL,35),
('Jefo de Unidad de Gobierno Electrónico ','JEFA (E) DE UNIDAD','169',8554,5,NULL,NULL,40,NULL),
('Técnico de Promoción y Desarrollo TIC ́s ','PROFESIONAL I','170',6000,9,NULL,NULL,40,NULL),
('Técnica I de Desarrollo y Mantenimiento de TIC ́s ','PROFESIONAL II','171',4622,11,NULL,NULL,40,NULL),
('Técnica II de Desarrollo y Mantenimiento de TIC ́s ','PROFESIONAL II','172',4622,11,NULL,NULL,40,NULL),
('Técnico de Seguridad Informática e Infraestructura de Redes ','PROFESIONAL II','173',4622,11,NULL,NULL,40,NULL),
('Técnico I de Soporte y Mantenimiento de Equipos ','ADMINISTRATIVO II ','174',3347,17,NULL,NULL,40,NULL),
('Técnico II de Soporte y Mantenimiento de Equipos ','ADMINISTRATIVO II ','175',3347,17,NULL,NULL,40,NULL),
('Técnico III de Soporte y Mantenimiento de Equipos ','ADMINISTRATIVO II ','176',3347,17,NULL,NULL,40,NULL),
('Secretario – Asistente de la Unidad de Gobierno Electrónico. ','APOYO ADMINISTRATIVO II','177',2800,21,NULL,NULL,40,NULL),
('Secretario Departamental de Desarrollo Humano, Culturas y Turismo. ','SECRETARIA (O) DEPARTAMENTAL','178',10577,3,14,NULL,NULL,NULL),
('Administradoro – Coordinadora (or) de la SDDHCyT. ','PROFESIONAL I','179',6000,9,14,NULL,NULL,NULL),
('Secretaria – Asistente de la SDDHCyT ','APOYO ADMINISTRATIVO I ','180',3100,19,14,NULL,NULL,NULL),
('Chofer - Mensajero de la SDDHCyT ','APOYO ADMINISTRATIVO I ','181',3100,19,14,NULL,NULL,NULL),
('Responsable del Área de Seguimiento a Institutos Técnicos y Tecnológicos. ','PROFESIONAL I','182',6000,9,NULL,NULL,NULL,36),
('Técnico de Seguimiento a Institutos Técnicos y Tecnológicos. ','PROFESIONAL II','183',4622,11,NULL,NULL,NULL,36),
('Directora de Culturas y Turismo ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','184',9623,4,NULL,26,NULL,NULL),
('Técnico en Gestión del Turismo, Control y Fiscalización. ','PROFESIONAL II','185',4622,11,NULL,26,NULL,NULL),
('Técnico en Gestión del Patrimonial Cultural y Museos. ','PROFESIONAL II','186',4622,11,NULL,26,NULL,NULL),
('Técnico en Promoción del Patrimonio Cultural y Turístico. ','ADMINISTRATIVO I','187',3925,13,NULL,26,NULL,NULL),
('Asistente - Técnico en Gestión del Turismo, Control y Fiscalización. ','ADMINISTRATIVO II ','188',3347,17,NULL,26,NULL,NULL),
('Técnica de Información Histórica Departamental ','ADMINISTRATIVO II ','189',3347,17,NULL,26,NULL,NULL),
('Secretario – Asistente de la DCyT ','APOYO ADMINISTRATIVO II','190',2800,21,NULL,26,NULL,NULL),
('Chofer - Mensajero de la DCyT ','APOYO ADMINISTRATIVO II','191',2800,21,NULL,26,NULL,NULL),
('Directora Departamental del Deporte ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','192',9623,4,NULL,27,NULL,NULL),
('Técnico de la Dirección Departamental del Deporte ','PROFESIONAL II','193',4622,11,NULL,27,NULL,NULL),
('Secretaria – Asistente de la DIDEDE ','APOYO ADMINISTRATIVO II','194',2800,21,NULL,27,NULL,NULL),
('Chofer - Mensajero I de la DIDEDE ','APOYO ADMINISTRATIVO II','195',2800,21,NULL,27,NULL,NULL),
('Mensajero de la DIDEDE ','ASISTENTE ','196',2760,22,NULL,27,NULL,NULL),
('Responsable del Área de Desarrollo y Coordinación Deportiva. ','PROFESIONAL I','197',6000,9,NULL,NULL,NULL,37),
('Técnico I de Desarrollo y Coordinación Deportiva ','PROFESIONAL II','198',4622,11,NULL,NULL,NULL,37),
('Técnico II de Desarrollo y Coordinación Deportiva ','PROFESIONAL II','199',4622,11,NULL,NULL,NULL,37),
('Encargada I de la Piscina Alfredo Marquina ','APOYO ADMINISTRATIVO I ','200',3100,19,NULL,NULL,NULL,37),
('Encargado II de la Piscina Alfredo Marquina ','APOYO ADMINISTRATIVO I ','201',3100,19,NULL,NULL,NULL,37),
('Responsable del Área de Administración de Infraestructura Deportiva. ','PROFESIONAL I','202',6000,9,NULL,NULL,NULL,38),
('Encargado del Uso de Escenarios y Campos Deportivos ','ADMINISTRATIVO I','203',3925,13,NULL,NULL,NULL,38),
('Encargada del Cobro de Alquileres de infraestructura Deportiva.','APOYO ADMINISTRATIVO I ','204',3100,19,NULL,NULL,NULL,38),
('Técnico I en Mantenimiento de Infraestructura Deportiva.','APOYO ADMINISTRATIVO II','205',2800,21,NULL,NULL,NULL,38),
('Técnica (o) II en Mantenimiento de Infraestructura Deportiva. ','APOYO ADMINISTRATIVO II','206',2800,21,NULL,NULL,NULL,38),
('Asistente I en Mantenimiento de Infraestructura Deportiva. ','ASISTENTE ','207',2760,22,NULL,NULL,NULL,38),
('Asistente II en Mantenimiento de Infraestructura Deportiva. ','ASISTENTE ','208',2760,22,NULL,NULL,NULL,38),
('Asistente III en Mantenimiento de Infraestructura Deportiva. ','ASISTENTE ','209',2760,22,NULL,NULL,NULL,38),
('Asistente IV en Mantenimiento de Infraestructura Deportiva. ','ASISTENTE ','210',2760,22,NULL,NULL,NULL,38),
('Asistente V en Mantenimiento de Infraestructura Deportiva. ','ASISTENTE ','211',2760,22,NULL,NULL,NULL,38),
('Portero – Sereno I ','ASISTENTE ','212',2760,22,NULL,NULL,NULL,38),
('Portero – Sereno II ','ASISTENTE ','213',2760,22,NULL,NULL,NULL,38),
('Portero – Sereno III ','ASISTENTE ','214',2760,22,NULL,NULL,NULL,38),
('','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','215',9623,4,NULL,28,NULL,NULL),
('','PROFESIONAL I','216',6000,9,NULL,28,NULL,NULL),
('','PROFESIONAL I','217',6000,9,NULL,28,NULL,NULL),
('','PROFESIONAL I','218',6000,9,NULL,28,NULL,NULL),
('Secretario Departamental de Salud ','SECRETARIA (O) DEPARTAMENTAL','219',10577,3,15,NULL,NULL,NULL),
('Administradora – Coordinadora de la SDS ','PROFESIONAL I','220',6000,9,15,NULL,NULL,NULL),
('Secretaria – Asistente de la SDS ','APOYO ADMINISTRATIVO I ','221',3100,19,15,NULL,NULL,NULL),
('Chofer - Mensajero I de la SDS ','APOYO ADMINISTRATIVO I ','222',3100,19,15,NULL,NULL,NULL),
('Mensajero II de la SDS ','ASISTENTE','223',2760,22,15,NULL,NULL,NULL),
('Jefe de Unidad de Seguimiento a la Gestión de Salud. ','JEFA (E) DE UNIDAD','224',8554,5,NULL,NULL,41,NULL),
('Técnica en Seguimiento a la Gestión de Salud ','PROFESIONAL I','225',6000,9,NULL,NULL,41,NULL),
('Secretario Departamental de Gobernabilidad y Coordinación. ','SECRETARIA (O) DEPARTAMENTAL','226',10577,3,16,NULL,NULL,NULL),
('Administrador – Coordinador de la SDGyC ','PROFESIONAL I','227',6000,9,16,NULL,NULL,NULL),
('Secretaria – Asistente de la SDGyC ','APOYO ADMINISTRATIVO I ','228',3100,19,16,NULL,NULL,NULL),
('Chofer - Mensajero I de la SDGyC ','APOYO ADMINISTRATIVO I ','229',3100,19,16,NULL,NULL,NULL),
('Chofer - Mensajero II de la SDGyC ','APOYO ADMINISTRATIVO II','230',2800,21,16,NULL,NULL,NULL),
('Responsable de Personalidades Jurídicas ','PROFESIONAL I','231',6000,9,NULL,NULL,NULL,39),
('Técnica I de Personalidades Jurídicas ','PROFESIONAL II','232',4622,11,NULL,NULL,NULL,39),
('Técnica II de Personalidades Jurídicas ','PROFESIONAL II','233',4622,11,NULL,NULL,NULL,39),
('Asistente Administrativo de Personalidades Jurídicas ','APOYO ADMINISTRATIVO I ','234',3100,19,NULL,NULL,NULL,39),
('Director Técnico de Límites ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','235',9623,4,NULL,36,NULL,NULL),
('Técnica I de Límites y Organización Territorial ','PROFESIONAL I','236',6000,9,NULL,36,NULL,NULL),
('Técnico II de Límites y Organización Territorial ','PROFESIONAL II','237',4622,11,NULL,36,NULL,NULL),
('Técnico III de Límites y Organización Territorial ','PROFESIONAL II','238',4622,11,NULL,36,NULL,NULL),
('Técnico IV de Límites y Organización Territorial ','PROFESIONAL II','239',4622,11,NULL,36,NULL,NULL),
('Técnica V de Límites y Organización Territorial ','PROFESIONAL II','240',4622,11,NULL,36,NULL,NULL),
('Secretaria – Asistente de la DTL ','APOYO ADMINISTRATIVO II','241',2800,21,NULL,36,NULL,NULL),
('Director Departamental de Seguridad Ciudadana y Prevención. ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','242',9623,4,NULL,37,NULL,NULL),
('Técnica de Seguridad Ciudadana y Alerta Temprana. ','PROFESIONAL I','243',6000,9,NULL,37,NULL,NULL),
('Técnica de Seguridad Ciudadana y Prevención. ','PROFESIONAL II','244',4622,11,NULL,37,NULL,NULL),
('Secretaria – Asistente de la DDSCyP ','APOYO ADMINISTRATIVO II','245',2800,21,NULL,37,NULL,NULL),
('Jefa (e) de Unidad de Relacionamiento y Coordinación con Instituciones y Organizaciones Sociales. ','JEFA (E) DE UNIDAD','246',8554,5,NULL,NULL,42,NULL),
('Técnico de Coordinación con Instituciones y Organizaciones Sociales. ','PROFESIONAL I','247',6000,9,NULL,NULL,42,NULL),
('Técnica de Gestión y Coordinación – La Paz ','PROFESIONAL I','248',6000,9,NULL,NULL,42,NULL),
('Encargado de Relacionamiento Internacional e Interinstitucional. ','PROFESIONAL II','249',4622,11,NULL,NULL,42,NULL),
('Jefa de Unidad de Notaría de Gobierno ','JEFA (E) DE UNIDAD','250',8554,5,NULL,NULL,43,NULL),
('Técnica (o) en Notaría de Gobierno ','PROFESIONAL II','251',4622,11,NULL,NULL,43,NULL),
('Asistente Administrativo I de Notaria de Gobierno. ','APOYO ADMINISTRATIVO I ','252',3100,19,NULL,NULL,43,NULL),
('Asistente Administrativo II de Notaria de Gobierno. ','APOYO ADMINISTRATIVO I ','253',3100,19,NULL,NULL,43,NULL),
('Asistente Administrativo III de Notaria de Gobierno. ','APOYO ADMINISTRATIVO I ','254',3100,19,NULL,NULL,43,NULL),
('Asistente Administrativo IV de Notaria de Gobierno. ','APOYO ADMINISTRATIVO I ','255',3100,19,NULL,NULL,43,NULL),
('Secretario Departamental de Desarrollo Productivo ','SECRETARIA (O) DEPARTAMENTAL','256',10577,3,17,NULL,NULL,NULL),
('Administradora – Coordinadora de la SDDP ','PROFESIONAL I','257',6000,9,17,NULL,NULL,NULL),
('Secretaria – Asistente de la SDDP ','APOYO ADMINISTRATIVO I ','258',3100,19,17,NULL,NULL,NULL),
('Chofer - Mensajero de la SDDP ','APOYO ADMINISTRATIVO I ','259',3100,19,17,NULL,NULL,NULL),
('Asistente-Mensajero de la SDDP ','ASISTENTE ','260',2760,22,17,NULL,NULL,NULL),
('Director de Complejos Productivos e Industrialización ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','261',9623,4,NULL,38,NULL,NULL),
('Secretaria – Asistente de la DCPI ','APOYO ADMINISTRATIVO II','262',2800,21,NULL,38,NULL,NULL),
('Chofer – Mensajero de la DCPI ','APOYO ADMINISTRATIVO II','263',2800,21,NULL,38,NULL,NULL),
('Responsable del Área de Promoción de Complejos Productivos, Industria y Manufactura. ','PROFESIONAL I','264',6000,9,NULL,NULL,NULL,40),
('Técnico de Promoción y Comercialización de Productos, Industria y Manufactura. ','PROFESIONAL II','265',4622,11,NULL,NULL,NULL,40),
('Asistente Administrativo del APCPIyM ','APOYO ADMINISTRATIVO II','266',2800,21,NULL,NULL,NULL,40),
('Responsable de Área de Promoción de Mercados y MyPES. ','PROFESIONAL I','267',6000,9,NULL,NULL,NULL,41),
('Técnica de capacitación, promoción de mercados y MyPES. ','PROFESIONAL II','268',4622,11,NULL,NULL,NULL,41),
('Asistente Administrativo del APMyMyPES ','APOYO ADMINISTRATIVO II','269',2800,21,NULL,NULL,NULL,41),
('Director Departamental Agropecuario ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','270',9623,4,NULL,39,NULL,NULL),
('Secretario – Asistente de la DIDEAG ','APOYO ADMINISTRATIVO II','271',2800,21,NULL,39,NULL,NULL),
('Chofer – Mensajero de la DIDEAG ','APOYO ADMINISTRATIVO II','272',2800,21,NULL,39,NULL,NULL),
('Responsable de Área de Investigación y Seguridad Alimentaria ','PROFESIONAL I','273',6000,9,NULL,NULL,NULL,42),
('Técnico de Investigación y Seguridad Alimentaria - Región Valles. ','PROFESIONAL II','274',4622,11,NULL,NULL,NULL,42),
('Técnico de Investigación y Seguridad Alimentaria - Región Cono Sur. ','PROFESIONAL II','275',4622,11,NULL,NULL,NULL,42),
('Técnica de Investigación y Seguridad Alimentaria - Región Trópico. ','PROFESIONAL II','276',4622,11,NULL,NULL,NULL,42),
('Técnica (o) de Investigación y Seguridad Alimentaria - Región Andina. ','PROFESIONAL II','277',4622,11,NULL,NULL,NULL,42),
('Portero – Operador del Centro Experimental Tarata ','APOYO ADMINISTRATIVO II','278',2800,21,NULL,NULL,NULL,42),
('Portero – Operador del Centro Experimental San Benito ','APOYO ADMINISTRATIVO II','279',2800,21,NULL,NULL,NULL,42),
('Portero – Operador del Centro Experimental Mayra ','APOYO ADMINISTRATIVO II','280',2800,21,NULL,NULL,NULL,42),
('Portero – Operador del Centro Experimental Capinota ','APOYO ADMINISTRATIVO II','281',2800,21,NULL,NULL,NULL,42),
('Responsable de Área de Sanidad Agropecuaria e Inocuidad Alimentaria ','PROFESIONAL I','282',6000,9,NULL,NULL,NULL,43),
('Técnica I de Sanidad Agropecuaria e Inocuidad Alimentaria ','ADMINISTRATIVO II ','283',3347,17,NULL,NULL,NULL,43),
('Técnica II de Sanidad Agropecuaria e Inocuidad Alimentaria ','ADMINISTRATIVO II ','284',3347,17,NULL,NULL,NULL,43),
('Encargado de Área de Control y Fiscalización de Pesca y Comercialización. ','PROFESIONAL II','285',4622,11,NULL,NULL,NULL,44),
('Técnica I de Control y Fiscalización de Pesca y Comercialización. ','ADMINISTRATIVO II ','286',3347,17,NULL,NULL,NULL,44),
('Técnico II de Control y Fiscalización de Pesca y Comercialización. ','ADMINISTRATIVO II ','287',3347,17,NULL,NULL,NULL,44),
('Secretario Departamental de Minería, Hidrocarburos y Energías. ','SECRETARIA (O) DEPARTAMENTAL','288',10577,3,18,NULL,NULL,NULL),
('Administrador – Coordinador de la SDMHyE ','PROFESIONAL I','289',6000,9,18,NULL,NULL,NULL),
('Secretaria – Asistente de la SDMHyE ','APOYO ADMINISTRATIVO I ','290',3100,19,18,NULL,NULL,NULL),
('Chofer - Mensajero de la SDMHyE ','APOYO ADMINISTRATIVO I ','291',3100,19,18,NULL,NULL,NULL),
('Responsable del Área de Hidrocarburos y Energías ','PROFESIONAL I','292',6000,9,NULL,NULL,NULL,45),
('Técnica en Energías e Hidrocarburos ','PROFESIONAL II','293',4622,11,NULL,NULL,NULL,45),
('Director de Gestión y Desarrollo Minero ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','294',9623,4,NULL,40,NULL,NULL),
('Técnico I en Gestión y Desarrollo Minero ','PROFESIONAL I','295',6000,9,NULL,40,NULL,NULL),
('Técnica (o) II en Gestión y Desarrollo Minero ','PROFESIONAL I','296',6000,9,NULL,40,NULL,NULL),
('Chofer – Mensajero de la DGyDM ','APOYO ADMINISTRATIVO II','297',2800,21,NULL,40,NULL,NULL),
('Jefe de Unidad de Control y Fiscalización de Regalías ','JEFA (E) DE UNIDAD','298',8554,5,NULL,NULL,44,NULL),
('Técnico de Relacionamiento Minero-Social ','PROFESIONAL II','299',4622,11,NULL,NULL,44,NULL),
('Técnica de Fiscalización ','PROFESIONAL II','300',4622,11,NULL,NULL,44,NULL),
('Técnica I de Control y Fiscalización de la Regalía Minera ','ADMINISTRATIVO II ','301',3347,17,NULL,NULL,44,NULL),
('Técnico II de Control y Fiscalización de la Regalía Minera ','ADMINISTRATIVO II ','302',3347,17,NULL,NULL,44,NULL),
('Técnico III de Control y Fiscalización de la Regalía Minera ','ADMINISTRATIVO II ','303',3347,17,NULL,NULL,44,NULL),
('Técnica (o) IV de Control y Fiscalización de la Regalía Minera ','ADMINISTRATIVO II ','304',3347,17,NULL,NULL,44,NULL),
('Técnica (o) de Manejo y Sistematización del Formulario 101 ','ADMINISTRATIVO II ','305',3347,17,NULL,NULL,44,NULL),
('Secretaria Departamental de Medio Ambiente y Recursos Hídricos. ','SECRETARIA (O) DEPARTAMENTAL','306',10577,3,19,NULL,NULL,NULL),
('Administradora (or) - Coordinadora (or) de la SDMAyRH. ','PROFESIONAL I','307',6000,9,19,NULL,NULL,NULL),
('Secretaria – Asistente de la SDMAyRH ','APOYO ADMINISTRATIVO I ','308',3100,19,19,NULL,NULL,NULL),
('Chofer - Mensajero de la SDMAyRH ','APOYO ADMINISTRATIVO I ','309',3100,19,19,NULL,NULL,NULL),
('Director en Recursos Naturales y Riego ','DIRECTORA (OR)/DIR. SERV. DPTAL./VOCERA (O) GUB. ','310',9623,4,NULL,41,NULL,NULL),
('Técnico en Recursos Hídricos y Riego ','PROFESIONAL I','311',6000,9,NULL,41,NULL,NULL),
('Técnico en Biodiversidad y Recursos Forestales ','PROFESIONAL I','312',6000,9,NULL,41,NULL,NULL),
('Técnico en Agua Potable y Seguimiento ','PROFESIONAL II','313',4622,11,NULL,41,NULL,NULL),
('Secretario – Asistente de la DRNyR ','APOYO ADMINISTRATIVO II','314',2800,21,NULL,41,NULL,NULL),
('Chofer - Mensajero de la DRNyR ','APOYO ADMINISTRATIVO II','315',2800,21,NULL,41,NULL,NULL),
('Jefe de Unidad de Cuencas ','JEFA (E) DE UNIDAD','316',8554,5,NULL,NULL,45,NULL),
('Técnico en Manejo Integral de Cuencas ','PROFESIONAL I','317',6000,9,NULL,NULL,45,NULL),
('Técnico en Regulación y Encausamiento Hidráulico ','PROFESIONAL I','318',6000,9,NULL,NULL,45,NULL),
('Secretaria – Asistente de la Unidad de Cuencas ','APOYO ADMINISTRATIVO II','319',2800,21,NULL,NULL,45,NULL),
('Jefe de Unidad de Control y Fiscalización Ambiental ','JEFA (E) DE UNIDAD','320',8554,5,NULL,NULL,46,NULL),
('Técnica I en Control y Fiscalización Ambiental, Sector Recurso Hídrico. ','PROFESIONAL I','321',6000,9,NULL,NULL,46,NULL),
('Técnico II en Control y Fiscalización Ambiental, Sector Recurso Hídrico. ','PROFESIONAL I','322',6000,9,NULL,NULL,46,NULL),
('Técnica en Control y Fiscalización Ambiental, Sector Residuos Sólidos. ','PROFESIONAL I','323',6000,9,NULL,NULL,46,NULL),
('Técnica en Control y Fiscalización Ambiental, Sector Minería. ','PROFESIONAL I','324',6000,9,NULL,NULL,46,NULL),
('Técnica I en Control y Fiscalización Ambiental, Sector Multisectorial. ','PROFESIONAL I','325',6000,9,NULL,NULL,46,NULL),
('Técnico II en Control y Fiscalización Ambiental, Sector Multisectorial. ','PROFESIONAL II','326',4622,11,NULL,NULL,46,NULL),
('Técnica III en Control y Fiscalización Ambiental, Sector Multisectorial. ','PROFESIONAL II','327',4622,11,NULL,NULL,46,NULL),
('Técnico IV en Control y Fiscalización Ambiental, Sector Multisectorial. ','PROFESIONAL II','328',4622,11,NULL,NULL,46,NULL),
('Técnica Administrativo de Control y Fiscalización Ambiental, Sector Multisectorial. ','ADMINISTRATIVO II ','329',3347,17,NULL,NULL,46,NULL),
('Secretario – Asistente de la UCyFA ','APOYO ADMINISTRATIVO II','330',2800,21,NULL,NULL,46,NULL),
('Chofer - Mensajero de la UCyFA ','APOYO ADMINISTRATIVO II','331',2800,21,NULL,NULL,46,NULL),
('Jefa de Unidad de Gestión de Medio Ambiente ','JEFA (E) DE UNIDAD','332',8554,5,NULL,NULL,47,NULL),
('Técnico I en Gestión de Medio Ambiente ','PROFESIONAL I','333',6000,9,NULL,NULL,47,NULL),
('Técnico II en Gestión de Medio Ambiente ','PROFESIONAL II','334',4622,11,NULL,NULL,47,NULL),
('Jefe de Unidad de Gestión de Riesgos y Atención a Desastres. ','JEFA (E) DE UNIDAD','335',8554,5,NULL,NULL,48,NULL),
('Técnico de evaluación de daños y análisis de necesidades. ','ADMINISTRATIVO I','336',3925,13,NULL,NULL,48,NULL),
('Secretario – Asistente de la UGRyAD ','APOYO ADMINISTRATIVO II','337',2800,21,NULL,NULL,48,NULL),
('Chofer - Mensajero de la UGRyAD ','APOYO ADMINISTRATIVO II','338',2800,21,NULL,NULL,48,NULL),
('Secretario (a) Departamental de Obras y Servicios ','SECRETARIA (O) DEPARTAMENTAL','339',10577,3,20,NULL,NULL,NULL),
('Administrador – Coordinador  de la SDOyS ','PROFESIONAL I','340',6000,9,20,NULL,NULL,NULL),
('Secretaria – Asistente de la SDOyS ','APOYO ADMINISTRATIVO I ','341',3100,19,20,NULL,NULL,NULL),
('Chofer - Mensajero de la SDOyS ','APOYO ADMINISTRATIVO I ','342',3100,19,20,NULL,NULL,NULL),
('Mensajero-Asistente de la SDOyS ','ASISTENTE ','343',2760,22,20,NULL,NULL,NULL),
('Responsable del Área de Control y Fiscalización de Transporte y Telecomunicaciones. ','PROFESIONAL I','344',6000,9,NULL,NULL,NULL,46),
('Técnico Responsable de Control y Fiscalización de Transporte. ','PROFESIONAL I','345',6000,9,NULL,NULL,NULL,46),
('Técnico de Control y Fiscalización de Transporte y Telecomunicaciones. ','PROFESIONAL II','346',4622,11,NULL,NULL,NULL,46),
('Jefa de Unidad de Evaluación, Supervisión y Fiscalización de Obras. ','JEFA (E) DE UNIDAD','347',8554,5,NULL,NULL,49,NULL),
('Técnico I de Evaluación, Supervisión y Fiscalización de Obras. ','PROFESIONAL I','348',6000,9,NULL,NULL,49,NULL),
('Técnico II de Evaluación, Supervisión y Fiscalización de Obras. ','PROFESIONAL I','349',6000,9,NULL,NULL,49,NULL),
('Técnica III de Evaluación, Supervisión y Fiscalización de Obras. ','PROFESIONAL I','350',6000,9,NULL,NULL,49,NULL),
('Secretaria – Asistente de la UESyFO ','APOYO ADMINISTRATIVO II','351',2800,21,NULL,NULL,49,NULL),
('Chofer - Mensajero de la UESyFO ','APOYO ADMINISTRATIVO II','352',2800,21,NULL,NULL,49,NULL),
